const PasswordPolicy = {
    MIN_LENGTH: 6,
    MAX_LENGTH: 30,
    MIN_UPPERCASE: 1,
    MIN_DIGIT: 1,
    MIN_SPECIAL: 1,
    MIN_LOWERCASE: 1,
    ACCOUNT_lOCK_TIME: 30, // 30 minutes
    MAX_LOGIN_ATTEMPT: 3,
    PASSWORD_CHANGE_TIME: 90, // 90 days
    OLD_PASSWORD_LENGTH: 3,
    TOKEN_EXPIRE_TIME: "1d",
    IN_ACTIVITY_TIME: 60, // 15 minutes
  };
  const ResponseCodes = {
    OK: 200,
    CREATED: 201,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
    TOO_LARGE: 413,
    TOO_MANY_REQUEST: 429,
    INTERNAL_SERVER_ERROR: 500,
    ACCOUNT_LOCKED_ERROR: 418,
  };
  
  const UserResponseCodes = {
    USER_SUCCESS: 2001,
    USER_NOT_FOUND: 2002,
    USER_PASSWORD_KEY_ERROR: 2003,
    USER_ALREADY_EXIST: 2004,
    USER_PASSWORD_MATCH_ERROR: 2008,
    USER_FETCH_FAILED: 2009,
    USER_DELETED_ERROR: 2010,
    PASSWORD_SHOULD_NOT_SAME: 2011,
    USER_ALREADY_LOGIN:  2012,
    USER_PASSWORD_EXPIRES : 2013,
    PASSWORD_RESET_SUCCESS: 2014,
  };
export{PasswordPolicy,ResponseCodes,UserResponseCodes};